const products = [
    { id: "G01", name: "Fender", description: "Red Electric Guitar", price: 200000, discontinued: false, categories: ["GXX"], imageUrl: "Fender.jpg" },
    { id: "G03", name: "Charvel", description: "Maple Electric Guitar", price: 186596, discontinued: false, categories: ["GXX"], imageUrl: "charvel1.jpg"  },
    { id: "G05", name: "LTD", description: "Mahogany Bass Guitar", price: 175243, discontinued: false, categories: ["GXX"], imageUrl: "LTD.jpg"  },
    { id: "G07", name: "MJ Brown", description: "Mustang Bass Black", price: 153245, discontinued: true, categories: ["GXX"], imageUrl: "mjbrown.jpg"  },
    { id: "G09", name: "Walnut", description: "Kingman Acoustic Bass", price: 194728, discontinued: false, categories: ["GXX"], imageUrl: "walnut.jpg"  },
    { id: "D12", name: "Nix", description: "All Mesh Head Digital Drum Kit", price: 299900, discontinued: false, categories: ["DRXX"], imageUrl: "NIx.jpg " },
    { id: "D14", name: "Pearl", description: "Electric Merge Drum Kit", price: 87600, discontinued: false, categories: ["DRXX"], imageUrl: "pearl.jpg "  },
    { id: "D16", name: "Yamaha", description: "5-Piece Electronic Kit", price: 97600, discontinued: false, categories: ["DRXX"], imageUrl: "yamaha.jpg " },
    { id: "D18", name: "Gretsch", description: "4 Piece Drum Shell Pack", price: 321373, discontinued: false, categories: ["DRXX"], imageUrl: "gretsch.jpg "  },
    { id: "D20", name: "VOX", description: "Renown Vintage Pearl Kit", price: 291264, discontinued: false, categories: ["DRXX"], imageUrl: "vox1.jpg "  },
    { id: "V3", name: "Midnight", description: "Tower String Starter Violin", price: 29600, discontinued: false, categories: ["VIXX"], imageUrl: "midnight.jpg "  },
    { id: "V4", name: "Entertainer", description: "Pink Scotties Violin", price: 28900, discontinued: false, categories: ["VIXX"], imageUrl: "entertainer.jpg "  },
    { id: "V7", name: "OB1", description: "Fiddlerman Violin Outfit", price: 149000, discontinued: false, categories: ["VIXX"], imageUrl: "OB1.jpg "  },
    { id: "V98", name: "905", description: "Ming Jiang Zhu Violin", price: 39900, discontinued: false, categories: ["VIXX"], imageUrl: "9051.jpg "  },
    { id: "V56", name: "Holstein", description: "Bench Strad 1715 Violin", price: 390000, discontinued: true, categories: ["VIXX"], imageUrl: "holstein.jpg "  },
    { id: "KY99", name: "ROLAND", description: "88-Key Digital Piano", price: 34900, discontinued: false, categories: ["KYXX"], imageUrl: "roland1.jpg "  },
    { id: "KY98", name: "N1X", description: "Avant Grand Hybrid Digital Piano", price: 45600, discontinued: false, categories: ["KYXX"], imageUrl: "N1X2.jpg "  },
    { id: "KY97", name: "Korg", description: "Lightweight Action Portable Keyboard", price: 23400, discontinued: false, categories: ["KYXX"], imageUrl: "korg.jpg "  },
    { id: "KY96", name: "Press", description: "48 Note Symphony Portable Keyboard", price: 54600, discontinued: false, categories: ["KYXX"], imageUrl: "press1.jpg "  },
    { id: "KY00", name: "Artery", description: "Beatstep Pro-Pad Controller", price: 32400, discontinued: true, categories: ["KYXX"], imageUrl: "artery.jpg "  },
    { id: "AC75", name: "Blackstar", description: "Button Footswitch", price: 14995, discontinued: false, categories: ["ACXX"], imageUrl: "blackstar.jpg "  },
    { id: "AC76", name: "Bassman", description: "Head120V Amp", price: 171999, discontinued: false, categories: ["ACXX"], imageUrl: "bassman.jpg "  },
    { id: "AC77", name: "Rumble", description: "800HD 120V AMP", price: 102999, discontinued: false, categories: ["ACXX"], imageUrl: "rumble1.jpg "  },
    { id: "AC78", name: "Gator", description: "Keyboard Carrying Bag", price: 7500, discontinued: true, categories: ["ACXX"], imageUrl: "gator.jpg "  },
    { id: "AC79", name: "Crossrock", description: "Economy keyboard bag", price: 8999, discontinued: false, categories: ["ACXX"], imageUrl: "crossrock.jpg "  },
  ];